#!/bin/sh
# Resolve + hash-pin the deployment dependency set for CPython 3.12 on
# linux, once per target architecture. Runs inside the deployment
# interpreter; invoked by scripts/lock-requirements.sh.
#
# Per-architecture files are a requirement, not a convenience: some wheels
# are published for only one architecture at a given version (mediapipe
# lags on aarch64), so a merged lock would carry two conflicting pins for
# the same package and fail to install.
set -eu
OUT=/out
cd /repo

emit() {   # emit <arch-tag> <requirement files...>
  arch="$1"; shift
  lock="requirements-full-${arch}.lock"
  rm -rf /tmp/w; mkdir -p /tmp/w
  echo ">>> resolving $lock" >&2
  # shellcheck disable=SC2046
  pip download -q --only-binary=:all: \
    --python-version 3.12 --implementation cp --abi cp312 \
    --platform "manylinux2014_${arch}" \
    --platform "manylinux_2_17_${arch}" \
    --platform "manylinux_2_28_${arch}" \
    --platform "manylinux_2_31_${arch}" \
    --platform "manylinux_2_35_${arch}" \
    --platform "manylinux_2_39_${arch}" \
    --dest /tmp/w $(for f in "$@"; do printf -- '-r %s ' "$f"; done) >&2
  {
    echo "# Generated by scripts/lock-requirements.sh — do not edit by hand."
    echo "# Target: CPython 3.12, linux/${arch} (manylinux)."
    echo "# Install with:  pip install --require-hashes -r ${lock}"
    echo "#"
    for whl in $(ls /tmp/w | sort); do
      name=$(echo "$whl" | cut -d- -f1 | tr '_' '-')
      ver=$(echo "$whl" | cut -d- -f2)
      echo "${name}==${ver}|$(pip hash "/tmp/w/$whl" | tail -1 | tr -d ' ')"
    done | sort -u | awk -F'|' '
      { if ($1 != prev) { if (prev != "") printf "\n"; printf "%s", $1; prev=$1 }
        printf " \\\n    %s", $2 }
      END { printf "\n" }'
  } > "$OUT/$lock"
  echo ">>> wrote $lock ($(grep -c '==' "$OUT/$lock") packages)" >&2
}

pip install -q --upgrade pip >&2
emit x86_64  requirements.txt requirements-optional.txt
emit aarch64 requirements.txt requirements-optional.txt
